/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

/**
 *
 * @author cherly
 */
public class Dashboard1_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard1
     */
    public Dashboard1_Frame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDashbord = new javax.swing.JButton();
        btnDataSantri = new javax.swing.JButton();
        btnPengurus = new javax.swing.JButton();
        btnJariyah = new javax.swing.JButton();
        btnSyariah = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.CardLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 1030, 660));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Dasboard Utama Mentahan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, -1));

        btnDashbord.setText("jButton1");
        btnDashbord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashbordActionPerformed(evt);
            }
        });
        getContentPane().add(btnDashbord, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, -1));

        btnDataSantri.setText("jButton2");
        btnDataSantri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataSantriActionPerformed(evt);
            }
        });
        getContentPane().add(btnDataSantri, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 120, -1));

        btnPengurus.setText("jButton3");
        btnPengurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengurusActionPerformed(evt);
            }
        });
        getContentPane().add(btnPengurus, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 140, -1));

        btnJariyah.setText("jButton4");
        getContentPane().add(btnJariyah, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 90, -1));

        btnSyariah.setText("jButton5");
        btnSyariah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSyariahActionPerformed(evt);
            }
        });
        getContentPane().add(btnSyariah, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 100, -1));

        btnClose.setText("jButton1");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 50, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSyariahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSyariahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSyariahActionPerformed

    private void btnDashbordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashbordActionPerformed
        // TODO add your handling code here:
        jPanel1.removeAll();
        jPanel1.add(new Dashboard2_Frame());
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_btnDashbordActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnDataSantriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataSantriActionPerformed
        // TODO add your handling code here:
        jPanel1.removeAll();
        jPanel1.add(new SantriFrame());
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_btnDataSantriActionPerformed

    private void btnPengurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengurusActionPerformed
        // TODO add your handling code here:
        jPanel1.removeAll();
        jPanel1.add(new PengurusFrame());
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_btnPengurusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard1_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard1_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard1_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard1_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard1_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDashbord;
    private javax.swing.JButton btnDataSantri;
    private javax.swing.JButton btnJariyah;
    private javax.swing.JButton btnPengurus;
    private javax.swing.JButton btnSyariah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
