/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frame;

import kelas.Dashboard2;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author cherly
 */
public class Dashboard2_Frame extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard2
     */
    public Dashboard2_Frame() {
        initComponents();
        JmlhDashboard();
    }
    
    private void JmlhDashboard() {
        try {
        Dashboard2 Dsh2 = new Dashboard2();

        // Ambil jumlah santri
        ResultSet rsSantri = Dsh2.JumlahSantri();
        int santri = 0;
        if (rsSantri.next()) {
            santri = rsSantri.getInt("jumlahS");
        }

        // Ambil jumlah pengurus
        ResultSet rsPengurus = Dsh2.JumlahPengurus();
        int pengurus = 0;
        if (rsPengurus.next()) {
            pengurus = rsPengurus.getInt("jumlahP");
        }

        // Tampilkan
        jmlSantri.setText(String.valueOf(santri));
        jmlPengurus.setText(String.valueOf(pengurus));

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "EROR : " + e.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dashboard = new javax.swing.JPanel();
        jmlPengurus = new javax.swing.JLabel();
        jmlSantri = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jmlPengurus.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jmlPengurus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlPengurus.setText("23");
        dashboard.add(jmlPengurus, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 170, 100));

        jmlSantri.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jmlSantri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlSantri.setText("23");
        dashboard.add(jmlSantri, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 170, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Dashboard2 Mentahan.png"))); // NOI18N
        dashboard.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mainPanel.add(dashboard, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jmlPengurus;
    private javax.swing.JLabel jmlSantri;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
