/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frame;

/**
 *
 * @author cherly
 */
public class InputSantriFrame extends javax.swing.JPanel {

    /**
     * Creates new form InputSantriFrame
     */
    public InputSantriFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tNamaLengkap = new javax.swing.JTextField();
        tTempatLahir = new javax.swing.JTextField();
        jTanggalMasuk = new com.toedter.calendar.JDateChooser();
        jTanggalLahir = new com.toedter.calendar.JDateChooser();
        tAlamat = new javax.swing.JTextField();
        tWaliSantri = new javax.swing.JTextField();
        tNo = new javax.swing.JTextField();
        cStatus = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        btnBatatl = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(945, 589));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tNamaLengkap.setOpaque(true);
        add(tNamaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 152, 360, 30));

        tTempatLahir.setOpaque(true);
        add(tTempatLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 360, 30));
        add(jTanggalMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 312, 370, 40));
        add(jTanggalLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 310, 370, 40));

        tAlamat.setOpaque(true);
        add(tAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 360, 40));

        tWaliSantri.setOpaque(true);
        add(tWaliSantri, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 360, 30));

        tNo.setOpaque(true);
        add(tNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 360, 40));

        cStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mukim", "Tidak Mukim" }));
        cStatus.setOpaque(true);
        add(cStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 392, 370, 40));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButton1.setText("Laki-Laki");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 120, 40));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButton2.setText("Perempuan");
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 130, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Santri Input (2).png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 950, 590));

        btnBatatl.setText("jButton1");
        btnBatatl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatatlActionPerformed(evt);
            }
        });
        add(btnBatatl, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, 80, 30));

        btnReset.setText("jButton2");
        add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 90, 30));

        btnSimpan.setText("jButton3");
        add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 463, 80, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void btnBatatlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatatlActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBatatlActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatatl;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cStatus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private com.toedter.calendar.JDateChooser jTanggalLahir;
    private com.toedter.calendar.JDateChooser jTanggalMasuk;
    private javax.swing.JTextField tAlamat;
    private javax.swing.JTextField tNamaLengkap;
    private javax.swing.JTextField tNo;
    private javax.swing.JTextField tTempatLahir;
    private javax.swing.JTextField tWaliSantri;
    // End of variables declaration//GEN-END:variables
}
