/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frame;

/**
 *
 * @author cherly
 */
public class KelasPanel extends javax.swing.JPanel {

    /**
     * Creates new form KelasPanel
     */
    public KelasPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tNama = new javax.swing.JTextField();
        tID3 = new javax.swing.JTextField();
        tID = new javax.swing.JTextField();
        btnBatal = new javax.swing.JLabel();
        btnReset = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cWaliKelas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(35, 64, 60));
        jLabel2.setText("DATA KELAS");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 310, 60));

        jLabel7.setBackground(new java.awt.Color(218, 241, 222));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(35, 64, 60));
        jLabel7.setText(" Nama Kelas");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 110, 30));

        jLabel8.setBackground(new java.awt.Color(218, 241, 222));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(35, 64, 60));
        jLabel8.setText(" Wali Kelas");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 110, 30));

        jLabel9.setBackground(new java.awt.Color(218, 241, 222));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(35, 64, 60));
        jLabel9.setText(" ID Kelas");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 110, 30));

        tNama.setBorder(null);
        tNama.setOpaque(true);
        add(tNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 360, 30));

        tID3.setBorder(null);
        tID3.setOpaque(true);
        add(tID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 290, 30));

        tID.setBorder(null);
        tID.setOpaque(true);
        add(tID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 360, 30));

        btnBatal.setBackground(new java.awt.Color(218, 241, 222));
        btnBatal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(218, 241, 222));
        btnBatal.setText("  Batal");
        add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 60, 40));

        btnReset.setBackground(new java.awt.Color(218, 241, 222));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(218, 241, 222));
        btnReset.setText("  Reset");
        add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 70, 40));

        btnSimpan.setBackground(new java.awt.Color(218, 241, 222));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(218, 241, 222));
        btnSimpan.setText("  Simpan");
        add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 80, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 490, 550));

        cWaliKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cWaliKelas.setBorder(null);
        cWaliKelas.setOpaque(true);
        add(cWaliKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 352, 370, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Data_Kelas.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBatal;
    private javax.swing.JLabel btnReset;
    private javax.swing.JLabel btnSimpan;
    private javax.swing.JComboBox<String> cWaliKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tID;
    private javax.swing.JTextField tID3;
    private javax.swing.JTextField tNama;
    // End of variables declaration//GEN-END:variables
}
