/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frame;

/**
 *
 * @author cherly
 */
public class KitabPanel extends javax.swing.JPanel {

    /**
     * Creates new form KitabPanel
     */
    public KitabPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnReset = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JLabel();
        btnBatal = new javax.swing.JLabel();
        tNama = new javax.swing.JTextField();
        tID = new javax.swing.JTextField();
        cPengajar = new javax.swing.JComboBox<>();
        cKelas = new javax.swing.JComboBox<>();
        tID1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(35, 64, 60));
        jLabel3.setText("Nama Kitab");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 110, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(35, 64, 60));
        jLabel2.setText("DATA KITAB");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 310, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(35, 64, 60));
        jLabel4.setText("Kelas");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 110, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(35, 64, 60));
        jLabel5.setText("Pengajar");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 110, -1));

        btnReset.setBackground(new java.awt.Color(218, 241, 222));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(218, 241, 222));
        btnReset.setText(" Reset");
        add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 70, 40));

        jLabel7.setBackground(new java.awt.Color(218, 241, 222));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(35, 64, 60));
        jLabel7.setText("ID Kitab");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 110, -1));

        btnSimpan.setBackground(new java.awt.Color(218, 241, 222));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(218, 241, 222));
        btnSimpan.setText("Simpan");
        add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 70, 40));

        btnBatal.setBackground(new java.awt.Color(218, 241, 222));
        btnBatal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(218, 241, 222));
        btnBatal.setText("Batal");
        add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 475, 50, 30));

        tNama.setBorder(null);
        tNama.setOpaque(true);
        tNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaActionPerformed(evt);
            }
        });
        add(tNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 360, 30));

        tID.setBorder(null);
        tID.setOpaque(true);
        add(tID, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 290, 30));

        cPengajar.setBorder(null);
        cPengajar.setOpaque(true);
        add(cPengajar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 360, 30));

        cKelas.setBorder(null);
        cKelas.setOpaque(true);
        add(cKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 360, 30));

        tID1.setBorder(null);
        tID1.setOpaque(true);
        add(tID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 360, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Data_Kitab.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBatal;
    private javax.swing.JLabel btnReset;
    private javax.swing.JLabel btnSimpan;
    private javax.swing.JComboBox<String> cKelas;
    private javax.swing.JComboBox<String> cPengajar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tID;
    private javax.swing.JTextField tID1;
    private javax.swing.JTextField tNama;
    // End of variables declaration//GEN-END:variables
}
