/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frame;

import kelas.Santri;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;




/**
 *
 * @author cherly
 */
public class SantriFrame extends javax.swing.JPanel {

    public SantriFrame() {
        initComponents();
        JmlhSantri();
        load_table();
        reset();
    }
    
    void reset() {
        tNamaLengkap.setText(null);
        tTempatLahir.setText(null);
        jTanggalLahir.setCalendar(null);
        tAlamat.setText(null);
        buttonGroup1.clearSelection();
        tWaliSantri.setText(null);
        tNo.setText(null);
        jTanggalMasuk.setCalendar(null);
        cStatus.setSelectedItem(null);
    }
    
    private void JmlhSantri() {
    try {
        Santri snt = new Santri();

        // Ambil Putra
        ResultSet rsPutra = snt.JumlahPutra();
        int putra = 0;
        if (rsPutra.next()) {
            putra = rsPutra.getInt("jumlahPutra");
        }

        // Ambil Putri
        ResultSet rsPutri = snt.JumlahPutri();
        int putri = 0;
        if (rsPutri.next()) {
            putri = rsPutri.getInt("jumlahPutri");
        }

        // Set ke label
        jmlSantriPutra.setText(String.valueOf(putra));
        jmlSantriPutri.setText(String.valueOf(putri));

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "EROR : " + e.getMessage());
    }
}
    
    private void pencarian(String key) {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Santri");
    model.addColumn("Nama");
    model.addColumn("Tempat Lahir");
    model.addColumn("Tanggal Lahir");
    model.addColumn("Alamat");
    model.addColumn("Gender");
    model.addColumn("Wali Santri");
    model.addColumn("No HP");
    model.addColumn("Tanggal Masuk");
    model.addColumn("Status");

    try {
        Santri snr = new Santri();
        ResultSet result = snr.cariSantri  (key);

        while (result.next()) {
            String status = (result.getInt("status") == 1) ? "Mukim" : "Tidak Mukim";
            model.addRow(new Object[]{
                result.getInt("id_santri"),
                result.getString("nama_santri"),
                result.getString("tempat_lahir"),
                result.getString("tanggal_lahir"),
                result.getString("alamat"),
                result.getString("jenis_kelamin"),
                result.getString("wali_santri"),
                result.getString("no_hp"),
                result.getString("tanggal_masuk"),
                status
            });
        }

        tblSantri.setModel(model);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error saat mencari: " + e.getMessage());
    }
}
    
    void load_table() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Santri");
        model.addColumn("Nama");
        model.addColumn("Tempat Lahir");
        model.addColumn("Tanggal Lahir");
        model.addColumn("Alamat");
        model.addColumn("Gender"); 
        model.addColumn("Wali Santri");
        model.addColumn("No HP");
        model.addColumn("Tanggal Masuk");
        model.addColumn("Status");
        
        try {
            Santri snr = new Santri();
            ResultSet result = snr.TampilSantri();
            while (result.next()){
                String status = (result.getInt("status") == 1) ? "Mukim" : "Tidak Mukim";
                model.addRow(new Object[]{
                    result.getInt("id_santri"),
                    result.getString("nama_santri"),
                    result.getString("tempat_lahir"),
                    result.getString("tanggal_lahir"),
                    result.getString("alamat"),
                    result.getString("jenis_kelamin"),
                    result.getString("wali_santri"),
                    result.getString("no_hp"),
                    result.getString("tanggal_masuk"),
                    status
                });
            }
            tblSantri.setModel(model);
        } catch (SQLException sQLException) {
            System.out.println("Eror : " + sQLException.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanelS = new javax.swing.JPanel();
        dataSantri = new javax.swing.JPanel();
        jmlSantriPutra = new javax.swing.JLabel();
        jmlSantriPutri = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSantri = new javax.swing.JTable();
        tSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        InputSantri = new javax.swing.JPanel();
        tNamaLengkap = new javax.swing.JTextField();
        tTempatLahir = new javax.swing.JTextField();
        tAlamat = new javax.swing.JTextField();
        tWaliSantri = new javax.swing.JTextField();
        tNo = new javax.swing.JTextField();
        cStatus = new javax.swing.JComboBox<>();
        jrLaki = new javax.swing.JRadioButton();
        jrPerempuan = new javax.swing.JRadioButton();
        tID = new javax.swing.JTextField();
        jTanggalMasuk = new com.toedter.calendar.JDateChooser();
        jTanggalLahir = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainPanelS.setLayout(new java.awt.CardLayout());

        dataSantri.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jmlSantriPutra.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jmlSantriPutra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlSantriPutra.setText("23");
        dataSantri.add(jmlSantriPutra, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 200, 90));

        jmlSantriPutri.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jmlSantriPutri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlSantriPutri.setText("34");
        dataSantri.add(jmlSantriPutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 200, 90));

        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tblSantri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSantri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSantriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSantri);

        dataSantri.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 970, 320));

        tSearch.setBorder(null);
        tSearch.setOpaque(true);
        tSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tSearchMouseClicked(evt);
            }
        });
        tSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tSearchKeyTyped(evt);
            }
        });
        dataSantri.add(tSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 150, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Data Santri Mentahan.png"))); // NOI18N
        dataSantri.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        btnTambah.setText("jButton1");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        dataSantri.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 100, 40));

        btnUbah.setText("jButton3");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        dataSantri.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 100, 30));

        btnHapus.setText("jButton2");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        dataSantri.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 100, 40));

        mainPanelS.add(dataSantri, "card2");

        InputSantri.setMinimumSize(new java.awt.Dimension(945, 589));
        InputSantri.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tNamaLengkap.setBorder(null);
        tNamaLengkap.setOpaque(true);
        InputSantri.add(tNamaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 152, 360, 30));

        tTempatLahir.setBorder(null);
        tTempatLahir.setOpaque(true);
        tTempatLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTempatLahirActionPerformed(evt);
            }
        });
        InputSantri.add(tTempatLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 238, 360, 20));

        tAlamat.setBorder(null);
        tAlamat.setOpaque(true);
        InputSantri.add(tAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 360, 20));

        tWaliSantri.setBorder(null);
        tWaliSantri.setOpaque(true);
        InputSantri.add(tWaliSantri, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 360, 20));

        tNo.setBorder(null);
        tNo.setOpaque(true);
        InputSantri.add(tNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 360, 20));

        cStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mukim", "Tidak Mukim" }));
        cStatus.setBorder(null);
        cStatus.setOpaque(true);
        InputSantri.add(cStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 392, 370, 40));

        buttonGroup1.add(jrLaki);
        jrLaki.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jrLaki.setText("Laki-Laki");
        jrLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrLakiActionPerformed(evt);
            }
        });
        InputSantri.add(jrLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 120, 40));

        buttonGroup1.add(jrPerempuan);
        jrPerempuan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jrPerempuan.setText("Perempuan");
        InputSantri.add(jrPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 130, 40));

        tID.setEnabled(false);
        InputSantri.add(tID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 270, -1));
        InputSantri.add(jTanggalMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 360, -1));
        InputSantri.add(jTanggalLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 360, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Santri Input (2).png"))); // NOI18N
        InputSantri.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 950, 590));

        btnBatal.setText("jButton1");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        InputSantri.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, 80, 30));

        btnReset.setText("jButton2");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        InputSantri.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 90, 30));

        btnSimpan.setText("jButton3");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        InputSantri.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 463, 80, 40));

        mainPanelS.add(InputSantri, "card3");

        add(mainPanelS, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
       
    int row = tblSantri.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(null, "Pilih dulu data di tabel!");
        return;
    }

    // Ambil ID Santri yang dipilih
    String idStr = tblSantri.getValueAt(row, 0).toString();
    int id = Integer.parseInt(idStr);

    try {
        // Ambil data lengkap dari database
        Santri str = new Santri();
        ResultSet rs = str.DetailSantri(id);  // Anda pastikan method ini ada

        if (rs.next()) {

            // Isi form

            tNamaLengkap.setText(rs.getString("nama_santri"));
            tTempatLahir.setText(rs.getString("tempat_lahir"));

            // tanggal lahir
            java.util.Date tglLahir = new SimpleDateFormat("yyyy-MM-dd")
                    .parse(rs.getString("tanggal_lahir"));
            jTanggalLahir.setDate(tglLahir);

            tAlamat.setText(rs.getString("alamat"));

            String gender = rs.getString("jenis_kelamin");
            if (gender.equals("Laki-Laki")) jrLaki.setSelected(true);
            else jrPerempuan.setSelected(true);

            tWaliSantri.setText(rs.getString("wali_santri"));
            tNo.setText(rs.getString("no_hp"));

            // tanggal masuk
            java.util.Date tglMasuk = new SimpleDateFormat("yyyy-MM-dd")
                    .parse(rs.getString("tanggal_masuk"));
            jTanggalMasuk.setDate(tglMasuk);

            cStatus.setSelectedItem(rs.getInt("status") == 1 ? "Mukim" : "Tidak Mukim");
        }

    } catch (SQLException | ParseException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
        // Pastikan InputSantriFrame punya constructor (int id)
        mainPanelS.removeAll();
        mainPanelS.add(InputSantri);
        mainPanelS.repaint();
        mainPanelS.revalidate();   
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        mainPanelS.removeAll();
        mainPanelS.add(InputSantri);
        mainPanelS.repaint();
        mainPanelS.revalidate();        
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        Santri str = new Santri();
        int baris = tblSantri.getSelectedRow();
        String idStr = tblSantri.getValueAt(baris, 0).toString();
        int id = Integer.parseInt(idStr);
        str.setId_santri(id);
        str.HapusSantri();
        load_table();
        reset();
    
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jrLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrLakiActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
       mainPanelS.removeAll();
       mainPanelS.add(dataSantri);
       mainPanelS.repaint();
       mainPanelS.revalidate();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        Santri str = new Santri();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

            str.setNama_santri(tNamaLengkap.getText());
            str.setTempat_lahir(tTempatLahir.getText());
            str.setTanggal_lahir(sdf.format(jTanggalLahir.getDate()));
            str.setAlamat(tAlamat.getText());

            // Ambil gender dari radio button
            String gender = "";
            if (jrLaki.isSelected()) {
                gender = "Laki-Laki";
            } else if (jrPerempuan.isSelected()) {
                gender = "Perempuan";
            }
            str.setJenis_kelamin(gender);
            str.setWali_santri(tWaliSantri.getText());
            str.setNo_hp(tNo.getText());
            str.setTanggal_masuk(sdf.format(jTanggalMasuk.getDate())); 
            
            if (cStatus.getSelectedItem().equals("Mukim")) {
            str.setStatus(1);
            } else {
                str.setStatus(0); 
            } 
            str.SimpanSantri();
            load_table();
            reset();
        mainPanelS.removeAll();
        mainPanelS.add(dataSantri);
        mainPanelS.repaint();
        mainPanelS.revalidate();
            

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tblSantriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSantriMouseClicked
        // TODO add your handling code here:
        int row = tblSantri.getSelectedRow();
        
        if (row != -1) {

            String id = tblSantri.getValueAt(row, 0).toString();
            String nama      = tblSantri.getValueAt(row, 1).toString();
            String tmptLahir = tblSantri.getValueAt(row, 2).toString();
            String tglLahir  = tblSantri.getValueAt(row, 3).toString();
            String alamat    = tblSantri.getValueAt(row, 4).toString();
            String gender    = tblSantri.getValueAt(row, 5).toString();
            String wali      = tblSantri.getValueAt(row, 6).toString();
            String NoHp      = tblSantri.getValueAt(row, 7).toString();
            String tglMasuk  = tblSantri.getValueAt(row, 8).toString();
            String status    = tblSantri.getValueAt(row, 9).toString();
            

            tID.setText(id);
            tNamaLengkap.setText(nama);
            tTempatLahir.setText(tmptLahir);
            
            // Set tanggal
            jTanggalLahir.setDate(java.sql.Date.valueOf(tglLahir));
            jTanggalMasuk.setDate(java.sql.Date.valueOf(tglMasuk));
            
            tAlamat.setText(alamat);
            
            if (gender.equals("Laki-Laki")) {
                jrLaki.setSelected(true);
            } else if (gender.equals("Perempuan")) {
                jrPerempuan.setSelected(true);
            }
            tWaliSantri.setText(wali);
            tNo.setText(NoHp);
            cStatus.setSelectedItem(status);
        }
    }//GEN-LAST:event_tblSantriMouseClicked

    private void tTempatLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTempatLahirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tTempatLahirActionPerformed

    private void tSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tSearchMouseClicked
        // TODO add your handling code here:
        tSearch.setText("");
    }//GEN-LAST:event_tSearchMouseClicked

    private void tSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tSearchKeyTyped
        // TODO add your handling code here:
        String key = tSearch.getText();
        pencarian(key);
    }//GEN-LAST:event_tSearchKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InputSantri;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cStatus;
    private javax.swing.JPanel dataSantri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jTanggalLahir;
    private com.toedter.calendar.JDateChooser jTanggalMasuk;
    private javax.swing.JLabel jmlSantriPutra;
    private javax.swing.JLabel jmlSantriPutri;
    private javax.swing.JRadioButton jrLaki;
    private javax.swing.JRadioButton jrPerempuan;
    private javax.swing.JPanel mainPanelS;
    private javax.swing.JTextField tAlamat;
    private javax.swing.JTextField tID;
    private javax.swing.JTextField tNamaLengkap;
    private javax.swing.JTextField tNo;
    private javax.swing.JTextField tSearch;
    private javax.swing.JTextField tTempatLahir;
    private javax.swing.JTextField tWaliSantri;
    private javax.swing.JTable tblSantri;
    // End of variables declaration//GEN-END:variables
}
